def inputRules():
    print()
    print("-------Input Rules -----------")
    print()
    print("For Order Two Matrix")
    print()
    print("Two integer values seperated by space on first line")
    print("Two integer values seperated by space on second line")
    print()
    print("For Order Three Matrix")
    print()
    print("Three integer values seperated by space on first line")
    print("Three integer values seperated by space on second line")
    print("Three integer values seperated by space on thrid line")
